# Generated by Django 5.2.5 on 2025-08-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='name',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('guest', 'Guest')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.ForeignKey(default='guest', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.rolemodel'),
        ),
    ]
